[package]
name = "xasida"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
minio = "0.1.0"
pdf2image = "0.1.2"
rdkafka = "0.37.0"
serde = { version = "1.0.134", features=["derive"] }
serde_json = "1.0.134"
tempfile = "3.16.0"
tokio = "1.43.0"

[workspace]
members = []
