[package]
name = "extractpdf"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
minio = "0.1.0"
pdf2image = "0.1.2"
rdkafka = { version = "0.37.0", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
