name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tag: ${{ github.ref_name }}
jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        run: |
          tar cfz linux.tar.gz -C target/release xasida
          gh release upload $TAG linux.tar.gz

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        run: |
          tar cfz macos_darwin.tar.gz -C target/release xasida
          gh release upload $TAG macos_darwin.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload a release file
        shell: bash
        run: |
          cd target/release
          7z a windows.zip xasida.exe
          gh release upload $TAG windows.zip
